### ISSUE TITLE
Support self-hosted Gitlab

### ISSUE THREAD

**Issue by Nisgrak** [tavyandy97/span-tree#30]
Allow use the extension in self-hosted instances with domains not related to gitlab.com

**Comment by tavyandy97** [comment]
Hey!  @Nisgrak 
We have released a new version (ie v0.0.2.0). It supports self-hosted instances along with stylus theming (tested with [gitlab-dark](https://gitlab.com/vednoc/dark-gitlab)). It has been approved by Mozilla Addons and you can test it there. However it has not been approved yet by Chrome webstore (due to CO⬛⬛⬛).

I will post an update on this issue whenever it gets approved by the Chrome webstore. Hope it gets approved soon!

**Comment by tavyandy97** [comment]
@Nisgrak 
The chrome version has been approved. Here is the [link](https://chrome.google.com/webstore/detail/spantree-gitlab-tree/gcjikeldobhnaglcoaejmdlmbienoocg). Please do check the support for self-hosted instances. If there is any more feedback please do get back to me.

**Comment by Nisgrak** [comment]
I updated the extension but has been disabled, I have to reactivate the extension because it needs more permissions. (Sorry the image in spanish)
![image](https://user-images.githubusercontent.com/19597708/82645763-b7316200-9c13-11ea-93af-bd58deea83ac.png)

**Comment by tavyandy97** [comment]
This is happening because in the previous versions we were only accessing domains having `www.gitlab.com`. Whereas now since we are supporting self-hosted instances, we need permissions for `<all_urls>`. Hence chrome prompts the user whenever the permissions are changed.
