### ISSUE TITLE
Can we have a setting to whitelist domains rather than having the extension need to access all sites

### ISSUE THREAD

**Issue by BrianGilbert** [tavyandy97/span-tree#35]
Having full access to all sites we visit seems way more than is really required. could we just have a whitelist of domains that it works on?

**Comment by vedanshgarg** [comment]
Hi Brian. Chrome extensions cannot dynamically alter Site Access. That is fixed by the manifest provided by the extension upon submission. And if we ask only permission for https://gitlab.com/*, the user can’t give more URL access to the extension as you can see in the screenshot below.
<img width="701" alt="Screenshot 2020-05-29 at 3 17 57 PM" src="https://user-images.githubusercontent.com/40305225/83257397-f3476280-a1d1-11ea-913b-174d6cd6ebfc.png">


If you are concerned about site access of this extension, you can manually whitelist sites by right-clicking on the extension’s icon and going into “Manage Extensions” and providing the extension access to specific sites using “Site access”.
<img width="686" alt="Screenshot 2020-05-29 at 2 57 00 PM" src="https://user-images.githubusercontent.com/40305225/83257462-0f4b0400-a1d2-11ea-9fec-9fcc258267bb.png">
